pre_production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: /solr/annex-ims
    read_timeout: 2
    open_timeout: 0.5

production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: /solr/annex-ims
    read_timeout: 2
    open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/development
    # path: /solr/annex-ims
    log_level: WARNING
    read_timeout: 2
    open_timeout: 0.5

test:
  solr:
    hostname: localhost
    port: 8981
    path: /solr/test
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  solr:
    hostname: localhost
    port: 8080
    path: /solr/annex-ims
    log_level: WARNING
    read_timeout: 2
    open_timeout: 0.5
